### ISSUE TITLE
Open in a new tab

### ISSUE THREAD

**Issue by yacoob** [fran-f/keypirinha-terminal-profiles#2]
Thank you very much for this useful package! Here's a feature suggestion: add an option to open a profile in a new tab in existing (last used?) Terminal window. Plus maybe an option to make that a default thing?

I'm not sure whether Windows Terminal supports this kind of operation tbh.

**Comment by fran-f** [comment]
Hello @yacoob!
I'd love to add that, but for the moment Windows Terminal doesn't support operations on an existing window. That's tracked by [issue #4472](https://github.com/microsoft/terminal/issues/4472) in their repository, so I'll keep an eye on it.

**Comment by Crimix** [comment]
I look forward to this being a possibility at some point 👍

**Comment by svraka** [comment]
I believe this is now possible, see https://github.com/microsoft/terminal/issues/4472#issuecomment-788153129.

**Comment by Crimix** [comment]
It is, and it works great :)

**Comment by fran-f** [comment]
I had missed that, finally! Get the [new release](https://github.com/fran-f/keypirinha-terminal-profiles/releases/tag/v1.9) and open tabs to your heart's content 🚀 

Thank you for bringing this up!
