### ISSUE TITLE
No profiles detected

### ISSUE THREAD

**Issue by Crimix** [fran-f/keypirinha-terminal-profiles#3]
Hi, when trying refresh, the profile index, an error is thrown in the console and no profiles are indexed.

The error is 
** ERROR: Error from Terminal-Profiles.TerminalProfiles.on_catalog: <class 'AttributeError'>: '_io.TextIOWrapper' object has no attribute 'getvalue'
Traceback (most recent call last):
  File "C:\Users\myname\Keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\TerminalProfiles.py", line 54, in on_catalog
  File "C:\Users\myname\Keypirinha\portable\Profile\InstalledPackages\Terminal-Profiles.keypirinha-package\lib\WindowsTerminalWrapper.py", line 35, in profiles

**Comment by fran-f** [comment]
Does that happen only when you refresh with "Keypirinha: Refresh Catalog"? Do profiles appear when you first start Keypirinha?

**Comment by Crimix** [comment]
No profiles when I first start Keypirinha. The error also shows up on startup

**Comment by fran-f** [comment]
Uhm... maybe I was using the wrong method to read the configuration file.
Could you try to install this version? https://github.com/fran-f/keypirinha-terminal-profiles/releases/tag/v1.3

Copy to the `InstalledPackages` directory, and restart Keypirinha.

**Comment by Crimix** [comment]
That versions works 👍

**Comment by fran-f** [comment]
Great, thanks for checking!
